#!/bin/bash -e

ARGS=""
PULL_COMMAND=0

while [[ $# -gt 0 ]]; do
  case $1 in
    pull)
      PULL_COMMAND=1
      ;;
    --repo)
      REPO="$2"

      if [ "$PULL_COMMAND" -eq 1 ] && [[ ! "$REPO" =~ http.* ]]
      then
        echo "[Hack Kustomize] Removing --repo" 1>&2
        ARGS="$ARGS $REPO/$3"
        shift
        shift
        shift
      else
        ARGS="$ARGS $1 $2"
        shift
        shift
      fi
      ;;
    *)
      ARGS="$ARGS $1"
      shift # past argument
      ;;
  esac
done

if [ -n "$OVERRIDE_HELM_CACHE_HOME" ]
then
  export HELM_CACHE_HOME="$OVERRIDE_HELM_CACHE_HOME"
fi

if [ -n "$OVERRIDE_HELM_CONFIG_HOME" ]
then
  export HELM_CONFIG_HOME="$OVERRIDE_HELM_CONFIG_HOME"
fi

if [ -n "$OVERRIDE_HELM_DATA_HOME" ]
then
  export HELM_DATA_HOME="$OVERRIDE_HELM_DATA_HOME"
fi

helm $ARGS
