#!/bin/bash -e

ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    --repo)
      REPO="$2"

      if [[ ! "$REPO" =~ http.* ]]
      then
        echo "[Hack Kustomize] Removing --repo" 1>&2
        ARGS="$ARGS $REPO/$3"
        shift
        shift
        shift
      else
        ARGS="$ARGS $1 $2"
        shift
        shift
      fi
      ;;
    *)
      ARGS="$ARGS $1"
      shift # past argument
      ;;
  esac
done

echo "helm $ARGS"
